### ISSUE TITLE
Please create separate repositories

### ISSUE THREAD

**Issue by tarsius** [pjones/elisp#1]
Could you please create separate repositories for packages that have nothing to do with one another? That would help users who install packages as git submodules and would also allow me to add the packages to the Emacsmirror. I am currently working (once more) to mirror all the packages that are available from Melpa. `bitlbee` is available from Melpa but not yet the Emacsmirror - so if you are inclined to split up this repository, but do not have the time to do it all now, then maybe you should start with that.

**Comment by pjones** [comment]
First one done: https://github.com/pjones/bitlbee-el

**Comment by tarsius** [comment]
Thanks a lot!
